[refactoring] handle collateral and fees at the transaction itself
smart-chain-fr/tokenomia pull request #41
Opened 2021-11-04 16:44 UTC by nhenin

2021-11-04 16:48 UTC, NaadiQmmr approved these changes

2021-11-05 09:07 UTC, augucharles requested changes

2021-11-05 09:07 UTC, augucharles commented on src/Tokenomia/Token/CLAPStyle/Burn.hs
> +        { txIns =  [FromWallet (txOutRef  utxoWithTokensToBurn)]
non empty

2021-11-05 09:07 UTC, augucharles commented on src/Tokenomia/Token/CLAPStyle/Mint.hs
> +        { txIns =  [FromWallet txOutRefToConsume]
non empty

2021-11-05 09:07 UTC, augucharles commented on src/Tokenomia/Token/Transfer.hs
> +        , txIns =  [FromWallet (txOutRef utxoWithToken)]
non empty

2021-11-05 09:07 UTC, augucharles commented on src/Tokenomia/Vesting/Retrieve.hs
> +
non empty

2021-11-05 09:07 UTC, augucharles commented on src/Tokenomia/Vesting/Vest.hs
> +        , txIns =  [FromWallet (txOutRef  utxoWithTokens)]
non empty

2021-11-05 09:07 UTC, augucharles commented on src/Tokenomia/Wallet/Collateral/Write.hs
> +        , txIns =  []
non empty

2021-11-08 12:54 UTC, augucharles approved these changes

2021-11-08 12:54 UTC, merged