PrivateSale Tests
smart-chain-fr/tokenomia pull request #66
Opened 2022-07-04 09:13 UTC by ahmr88

2022-07-18 10:28 UTC, samuelWilliams99 requested changes

2022-07-18 10:28 UTC, samuelWilliams99 commented on src/Tokenomia/Vesting/Sendings.hs
> +    { sendingsRecipientAddress :: Address
Why this change?

2022-07-18 10:28 UTC, samuelWilliams99 commented on src/Tokenomia/Vesting/Sendings.hs
> +        throwError . BlockFrostError . BlockfrostError $ "Values don't match "
Why the space?

2022-07-18 10:28 UTC, samuelWilliams99 commented on src/Tokenomia/Vesting/Sendings.hs
> +      flatVal <- liftEither $ safeHeadToRight . flattenValue . snd $ txValue
This is making the assumption that the Value input will be a singleton. We have no guarantee of this.
The correct logic would be to verified all elements in the flattenValue list against the txHash. This would be calling `sumRelevantValues` on each of the flattenValue results, and verifying the amount against the thd3 of each.
Something like
```hs
flatVals <- liftEither $ flattenValue . snd $ txValue
...
totalAmounts = flip sumRelevantValues bfVals <$> flatVals
sendingsAmount = thd3 <$> flatVal
valid = all (uncurry (==)) $ zip totalAmounts sendingsAmount
```

2022-07-18 10:28 UTC, samuelWilliams99 commented on src/Tokenomia/Vesting/Sendings.hs
> +verifyTxs' ::
If this is intended as a refactor, lets just add it, given the behaviour is verified to be correct

2022-07-18 10:28 UTC, samuelWilliams99 commented on src/Tokenomia/Vesting/Sendings.hs
> +      flatVal <- liftEither $ safeHeadToRight . flattenValue . snd $ txValue
Apologies, this is something that should have been caught in a previous PR, but unfortunately it wasn't

2022-07-18 10:28 UTC, samuelWilliams99 commented on test/Spec/Tokenomia/Vesting/Sendings.hs
> +    maybe (throwError $ BlockFrostError BlockfrostNotFound) pure (txMap Map.!? txh)
An alternative to the `maybe (throwError e) pure` pattern is `liftEither $ maybeToRight e`

2022-07-18 10:28 UTC, samuelWilliams99 commented on test/Spec/Tokenomia/Vesting/Sendings.hs
> +      ] -}
is this incomplete?

2022-07-18 10:28 UTC, samuelWilliams99 commented on test/Spec/Tokenomia/Vesting/Sendings.hs
> +    {- createTestData ::  -}
unfinished comment?

2022-07-18 10:28 UTC, samuelWilliams99 commented on test/Spec/Tokenomia/Vesting/Sendings.hs
> +-- Investment list doesn't contain matching txHash
When you say matching here, do you mean a hash that doesn't exist onchain?

2022-07-18 10:28 UTC, samuelWilliams99 commented on test/Spec/Tokenomia/Vesting/Sendings.hs
> +investmentListMismatch = undefined
If this is a testcase that should exist, but is undefinable because the source code doesn't catch it, we should fix the source

2022-07-18 10:28 UTC, samuelWilliams99 commented on tokenomia.cabal
> +    build-depends:
Why spaces?

2022-07-18 10:57 UTC, amirmrad commented on test/Spec/Tokenomia/Vesting/Sendings.hs
> +    maybe (throwError $ BlockFrostError BlockfrostNotFound) pure (txMap Map.!? txh)
Is there a reason why the latter is preferred, I'm asking since making the change will require adding `either` package to the `build-depends` of the tests suite.

2022-07-18 11:09 UTC, amirmrad commented on test/Spec/Tokenomia/Vesting/Sendings.hs
> +    maybe (throwError $ BlockFrostError BlockfrostNotFound) pure (txMap Map.!? txh)
Alright Ill add it

2022-07-18 11:20 UTC, samuelWilliams99 commented on src/Tokenomia/Vesting/Sendings.hs
> +      -- Is there always a single Asset per txhash? if not then use of safeHeadToRight is not necessary
There is not, there can be many

2022-07-18 11:20 UTC, samuelWilliams99 commented on src/Tokenomia/Vesting/Sendings.hs
> +    -- is error necessary here?
See the comment above about partial

2022-07-19 10:32 UTC, samuelWilliams99 commented on src/Tokenomia/Vesting/Sendings.hs
> +checkMalformedAddr addr =
This seems a useful helper, especially for the generation part, maybe we should move this (and `sequenceWhile`, while we're at it) to a util file

2022-07-19 11:34 UTC, amirmrad commented on src/Tokenomia/Vesting/Sendings.hs
> +checkMalformedAddr addr =
Ok, sounds good. Is there an existing file or shall I create a new one, and if so where?

2022-07-19 11:52 UTC, samuelWilliams99 commented on src/Tokenomia/Vesting/Sendings.hs
> +checkMalformedAddr addr =
Maybe Common.Address?

2022-07-19 11:53 UTC, samuelWilliams99 commented on src/Tokenomia/Vesting/Sendings.hs
> +checkMalformedAddr addr =
unsure about sequenceWhile though

2022-07-19 11:53 UTC, samuelWilliams99 commented on src/Tokenomia/Vesting/Sendings.hs
> +checkMalformedAddr addr =
not worth a new file just for that

2022-07-20 11:13 UTC, merged